# Generated by Django 5.2.5 on 2025-08-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='phone_number',
            new_name='applicant_phone',
        ),
    ]
